server:
   port: 8080
spring:
  cache:
      redis:
        use-key-prefix: true
        time-to-live: 1d
  redis:
    #数据库索引
    shiro:
      expire: 1800
    database: 0
    host: 127.0.0.1
    port: 6379
    password: info
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
  devtools:
    restart:
      enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/jimmy?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&useSSL=true
    username: root
    password: info
    driver-class-name: com.mysql.jdbc.Driver
    max-idle: 10
    max-active: 15
    max-lifetime: 86430000
    log-abandoned: true
    remove-abandoned: true
    remove-abandoned-timeout: 60
    sqlScriptEncoding: UTF-8
    initialization-mode: always
    continue-on-error: true
#mybatis
mybatis-plus:
  mapper-locations: classpath:/mapper/*/*Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.jimmy.rdf.*.entity
  typeEnumsPackage: com.jimmy.rdf.*.entity.enums
  global-config:
    # 数据库相关配置
    db-config:
      #主键类型  AUTO:"数据库ID自增", INPUT:"用户输入ID",ID_WORKER:"全局唯一ID (数字类型唯一ID)", UUID:"全局唯一ID UUID";
      id-type: id_worker
      #字段策略 IGNORED:"忽略判断",NOT_NULL:"非 NULL 判断"),NOT_EMPTY:"非空判断"
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #数据库大写下划线转换
      #capital-mode: true
      #逻辑删除配置（下面3个配置）@TableLogic
      logic-delete-value: 0
      logic-not-delete-value: 1
      sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
      # SQL 解析缓存，开启后多租户 @SqlParser 注解生效
      sql-parser-cache: true
    #刷新mapper 调试神器
    refresh: true
  # 原生配置
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
##logging
#logging:
#  level: warn